version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "mypgdb"
      POSTGRES_USER: "dbadmin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
       - 8080:8080

